[project]
name = "redis-k8s-view-counter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Avichai", email = "@" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
redis-k8s-view-counter = "redis_k8s_view_counter:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
